# Generated by Django 4.1.2 on 2022-10-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chainbreakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quant1',
            new_name='quantity',
        ),
    ]
