# Generated by Django 4.1.2 on 2022-10-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chainbreakers', '0003_transaction_buyorder_transaction_sellorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('curr_price', models.FloatField()),
                ('prev_price', models.FloatField()),
                ('step', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
