# Generated by Django 4.1.2 on 2022-10-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chainbreakers', '0005_alter_price_curr_price_alter_price_prev_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='quant',
            new_name='quantity',
        ),
    ]
